apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-worker-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-worker
  serviceName: "cache-worker"
  template:
    metadata:
      labels:
        app: cache-worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cache-worker
        image: ericmelz/cache-worker:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: cacheroot
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: cacheroot
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 1Gi
