apiVersion: v1
kind: Service
metadata:
  name: cache-router-svc
  labels:
    app: cache-router
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30004
    protocol: TCP
  selector:
    app: cache-router