apiVersion: v1
kind: Service
metadata:
  name: nginx-yow-svc
  labels:
    app: nginx-yow
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: nginx-yow