apiVersion: v1
kind: Service
metadata:
  name: router-demo-svc
  labels:
    app: router-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol: TCP
  selector:
    app: router-demo