apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eric-eks
  region: us-west-1

managedNodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 80
    privateNetworking: true
  - name: ng-2-routers
    labels: { role: routers }
    instanceType: m5.2xlarge
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
